---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: backend
        image: usman134/todo-backend:latest
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-svc:27017/TODO"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todo-app
spec:
  selector:
    app: todo-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
