name: CI

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for multi-platform builds, caching, etc.)
      - uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ usman134 }}
          password: ${{ usmantariq786 }}

      # 4. Build & push BACKEND image
      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: usman134/todo-backend:latest

      # 5. Build & push FRONTEND image
      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: usman134/todo-frontend:latest
